services:
  # API Gateway - Único servicio activo
  api-gateway:
    build: ./api-gateway
    container_name: pharmavida_api_gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      # Montar socket de Docker para ejecutar contenedores
      - /var/run/docker.sock:/var/run/docker.sock
      # Montar credenciales AWSd
      - ~/.aws/credentials:/root/.aws/credentials:ro
    restart: unless-stopped
    networks:
      - pharmavida_network

networks:
  pharmavida_network:
    driver: bridge